language:  python
python: "3.6"

env:
   - ADDON_ID=service.script.hue
     BRANCH=krypton
     
# command to install dependencies
install: 
  - pip install kodi-addon-checker

script:
  - kodi-addon-checker --branch $BRANCH
